pipeline {
	agent any
	stages {
		stage('Test') {
			agent {
				docker {
					image 'python/robotframework'
				}
			}
			steps {
				sh 'ping -c 4 ${Chassis}'
				echo 'working dir:'
				sh 'pwd'
				sh 'python -m robot --dryrun ./simple_traffic.txt'
				sh 'python -m robot --variable chassis:${Chassis} ./simple_traffic.txt'

			}
		}
	}
	post {
		always {
			publishHTML (target: [
			  allowMissing: false,
			  alwaysLinkToLastBuild: false,
			  keepAll: true,
			  reportDir: '../IxNetwork simple traffic@2',
			  reportFiles: 'report.html',
			  reportName: "Simple Traffic Test Report"
			])
		}
	}
}
